[package]
name = "better-console"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
flate2 = "1"
lazy_static = "1"
regex = "1"
rustbox = "0.11"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
