[package]
name = "better-console"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

[dependencies]
crossbeam = "0.4.1"
flate2 = "1.0.3"
lazy_static = "1.1.0"
regex = "1.0.5"
rustbox = "0.11.0"
serde = { version = "1.0.80", features = ["derive"] }
toml = "0.4.8"
