[package]
name = "better-console"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]

[dependencies]
crossbeam = "0.4.1"
flate2 = "1.0.3"
lazy_static = "1.1.0"
regex = "1.0.5"
rustbox = "0.11.0"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.8"
