[package]
name = "better-console"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

[dependencies]
crossbeam = "0.8.1"
flate2 = "1.0.24"
lazy_static = "1.4.0"
regex = "1.5.6"
rustbox = "0.11.0"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
